//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelediyeProject.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Cenaze> Cenazes { get; set; }
        public virtual DbSet<Dergi> Dergis { get; set; }
        public virtual DbSet<DergiSayfa> DergiSayfas { get; set; }
        public virtual DbSet<Dosya> Dosyas { get; set; }
        public virtual DbSet<DosyaHash> DosyaHashes { get; set; }
        public virtual DbSet<DosyaResim> DosyaResims { get; set; }
        public virtual DbSet<DosyaVideo> DosyaVideos { get; set; }
        public virtual DbSet<Duyuru> Duyurus { get; set; }
        public virtual DbSet<Galeri> Galeris { get; set; }
        public virtual DbSet<Haber> Habers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<KullaniciBirim> KullaniciBirims { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<ProgramAyar> ProgramAyars { get; set; }
        public virtual DbSet<ProgramLog> ProgramLogs { get; set; }
        public virtual DbSet<ProjeEtkinlik> ProjeEtkinliks { get; set; }
        public virtual DbSet<RadyoTv> RadyoTvs { get; set; }
        public virtual DbSet<Reklam> Reklams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tt_DosyaAcilmaNedenTip> tt_DosyaAcilmaNedenTip { get; set; }
        public virtual DbSet<tt_DosyaDurumTip> tt_DosyaDurumTip { get; set; }
        public virtual DbSet<tt_DosyaGonderilecekBirimTip> tt_DosyaGonderilecekBirimTip { get; set; }
        public virtual DbSet<tt_DosyaKonumTip> tt_DosyaKonumTip { get; set; }
        public virtual DbSet<tt_DosyaMesajTip> tt_DosyaMesajTip { get; set; }
        public virtual DbSet<tt_KullaniciIsletimSistemiTip> tt_KullaniciIsletimSistemiTip { get; set; }
        public virtual DbSet<tt_KullaniciRolTip> tt_KullaniciRolTip { get; set; }
        public virtual DbSet<tt_RadyoTvTip> tt_RadyoTvTip { get; set; }
        public virtual DbSet<Yonetici> Yoneticis { get; set; }
        public virtual DbSet<YoneticiMesaj> YoneticiMesajs { get; set; }
        public virtual DbSet<YoneticiResim> YoneticiResims { get; set; }
    }
}
