//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelediyeProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosya()
        {
            this.DosyaResims = new HashSet<DosyaResim>();
            this.DosyaVideos = new HashSet<DosyaVideo>();
        }
    
        public int DosyaKey { get; set; }
        public System.Guid KullaniciKey { get; set; }
        public int DosyaAcilmaNedenTipKey { get; set; }
        public int DosyaDurumTipKey { get; set; }
        public Nullable<int> DosyaGonderilecekBirimTipKey { get; set; }
        public Nullable<int> DosyaMesajTipKey { get; set; }
        public Nullable<int> DosyaKonumTipKey { get; set; }
        public string Mesaj { get; set; }
        public string Aciklama { get; set; }
        public string IpAdres { get; set; }
        public string Enlem { get; set; }
        public string Boylam { get; set; }
        public System.DateTime IslemZamani { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string IrtibatNo { get; set; }
        public System.Guid KayitKisiKey { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.Guid GuncelleKisiKey { get; set; }
        public System.DateTime GuncelleTarih { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual tt_DosyaAcilmaNedenTip tt_DosyaAcilmaNedenTip { get; set; }
        public virtual tt_DosyaDurumTip tt_DosyaDurumTip { get; set; }
        public virtual tt_DosyaKonumTip tt_DosyaKonumTip { get; set; }
        public virtual tt_DosyaGonderilecekBirimTip tt_DosyaGonderilecekBirimTip { get; set; }
        public virtual tt_DosyaMesajTip tt_DosyaMesajTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DosyaResim> DosyaResims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DosyaVideo> DosyaVideos { get; set; }
    }
}
