//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelediyeProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramAyar
    {
        public int ProgramAyarKey { get; set; }
        public string Baslik { get; set; }
        public string Kisaltma { get; set; }
        public string ResimUrl { get; set; }
        public string ServerAdres { get; set; }
        public string SayfaAdres { get; set; }
        public string GoogleApiKey { get; set; }
        public string AppleApiKey { get; set; }
        public string AppleSertifika { get; set; }
        public string KeyCode { get; set; }
        public string Limit { get; set; }
        public System.Guid KayitKisiKey { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.Guid GuncelleKisiKey { get; set; }
        public System.DateTime GuncelleTarih { get; set; }
    }
}
