//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelediyeProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadyoTv
    {
        public int RadyoTvKey { get; set; }
        public int RadyoTvTipKey { get; set; }
        public string Adi { get; set; }
        public string Link { get; set; }
        public string DosyaYolu { get; set; }
        public System.Guid KayitKisiKey { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.Guid GuncelleKisiKey { get; set; }
        public System.DateTime GuncelleTarih { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual tt_RadyoTvTip tt_RadyoTvTip { get; set; }
    }
}
