//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelediyeProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_DosyaKonumTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_DosyaKonumTip()
        {
            this.Dosyas = new HashSet<Dosya>();
        }
    
        public int DosyaKonumTipKey { get; set; }
        public string DosyaKonumTipAdi { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dosya> Dosyas { get; set; }
    }
}
